list: $/voices4budget/contents/models/comment/columns.yaml
modelClass: Voices4budget\Contents\Models\Comment
title: Comments
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'voices4budget/contents/comments/update/:id'
filter: $/voices4budget/contents/models/comment/scopes.yaml
