list: $/voices4budget/contents/models/category/columns.yaml
modelClass: Voices4budget\Contents\Models\Category
title: 'voices4budget.contents::lang.entity.category.singular'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'voices4budget/contents/categories/update/:id'
structure:
  showReorder: true
  dragRow: true
  showTree: true