name: 'voices4budget.contents::lang.entity.area.singular'
form: $/voices4budget/contents/models/area/fields.yaml
modelClass: Voices4budget\Contents\Models\Area
defaultRedirect: voices4budget/contents/areas
create:
    redirect: 'voices4budget/contents/areas/update/:id'
    redirectClose: voices4budget/contents/areas
update:
    redirect: voices4budget/contents/areas
    redirectClose: voices4budget/contents/areas
permissions:
    modelCreate: 'voices4budget.areas.write'
    modelUpdate: 'voices4budget.areas.write'
    modelDelete: 'voices4budget.areas.write'