list: $/voices4budget/contents/models/area/columns.yaml
modelClass: Voices4budget\Contents\Models\Area
title: 'voices4budget.contents::lang.entity.area.plural'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'voices4budget/contents/areas/update/:id'
filter: $/voices4budget/contents/models/area/scopes.yaml
structure:
    showTree: true
    showSorting: false
    maxDepth: 4
    treeExpanded: false