name: Stakeholders
modelClass: Voices4budget\Contents\Models\Stakeholder
form: $/voices4budget/contents/models/stakeholder/fields.yaml
defaultRedirect: voices4budget/contents/stakeholders
create:
    redirect: 'voices4budget/contents/stakeholders/update/:id'
    redirectClose: voices4budget/contents/stakeholders
update:
    redirect: voices4budget/contents/stakeholders
    redirectClose: voices4budget/contents/stakeholders
preview: {  }
permissions:
    modelCreate: 'voices4budget.stakeholders.write'
    modelUpdate: 'voices4budget.stakeholders.write'
    modelDelete: 'voices4budget.stakeholders.write'