list: $/voices4budget/contents/models/vote/columns.yaml
modelClass: Voices4budget\Contents\Models\Vote
title: Votes
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
showTree: false
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: $/voices4budget/contents/models/vote/scopes.yaml
requiredPermissions:
    recordDelete: 'voices4budget.votes.write'