name: Votes
form: $/voices4budget/contents/models/vote/fields.yaml
modelClass: Voices4budget\Contents\Models\Vote
defaultRedirect: voices4budget/contents/votes
create:
    redirect: 'voices4budget/contents/votes/update/:id'
    redirectClose: voices4budget/contents/votes
update:
    redirect: voices4budget/contents/votes
    redirectClose: voices4budget/contents/votes
permissions:
    modelCreate: 'voices4budget.votes.write'
    modelUpdate: 'voices4budget.votes.write'
    modelDelete: 'voices4budget.votes.write'