list: $/voices4budget/contents/models/votingsession/columns.yaml
modelClass: Voices4budget\Contents\Models\VotingSession
title: VotingSessions
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'voices4budget/contents/votingsessions/update/:id'
filter: $/voices4budget/contents/models/votingsession/scopes.yaml